# Module: NumPy Assignments
## Lesson: NumPy


### Assignment 1: Array Creation and Manipulation

1. Create a NumPy array of shape (5, 5) filled with random integers between 1 and 20. Replace all the elements in the third column with 1.
2. Create a NumPy array of shape (4, 4) with values from 1 to 16. Replace the diagonal elements with 0.



In [ ]:
import numpy as np 
from random import randint

arr1 = np.random.randint(1, 21 ,size=(5,5))
print(f'Array : \n {arr1}')

arr1[: ,2] =1
print(f'Modified Array: \n{arr1}')

Array : 
 [[ 9 14 13 10 11]
 [17 20  7 15 15]
 [11 15 18 12  3]
 [ 6  8  2 12 12]
 [ 6 10  3 18  6]]
Modified Array: 
[[ 9 14  1 10 11]
 [17 20  1 15 15]
 [11 15  1 12  3]
 [ 6  8  1 12 12]
 [ 6 10  1 18  6]]


In [17]:
arr2 = np.random.randint(1,17, size=(4,4))
print(f'Original Array : \n {arr2}')

np.fill_diagonal(arr2 ,0)
print(f'Modified Array : \n {arr2}')

Original Array : 
 [[15 15  5 11]
 [11 13 13  3]
 [14 13  8  1]
 [ 8  2  8  8]]
Modified Array : 
 [[ 0 15  5 11]
 [11  0 13  3]
 [14 13  0  1]
 [ 8  2  8  0]]


### Assignment 2: Array Indexing and Slicing

1. Create a NumPy array of shape (6, 6) with values from 1 to 36. Extract the sub-array consisting of the 3rd to 5th rows and 2nd to 4th columns.
2. Create a NumPy array of shape (5, 5) with random integers. Extract the elements on the border.



In [21]:
arr3 = np.random.randint(1,37, size=(6,6))
print(f' Original Array : \n {arr3}')

new_arr = arr3[0:3,0:3]
print(f'Modified Array : \n {new_arr}')

 Original Array : 
 [[ 4 25 29 22 16 15]
 [ 8 35  9 18 18  3]
 [28  2  7 25 15  9]
 [12 21  5 36 23 33]
 [15  6 10 15 26 13]
 [ 3  4 31 32 17  9]]
Modified Array : 
 [[ 4 25 29]
 [ 8 35  9]
 [28  2  7]]


In [33]:
arr4 = np.random.randint(1,25, size=(5,5))
print(f' Original Array : \n {arr4}')

border_elem = np.concatenate((arr4[0, :],arr4[1:-1,0], arr4[-1, :],arr4[1:-1,-1]))
print(f'Modified Array : \n {border_elem}')

 Original Array : 
 [[16 10 22 14 21]
 [ 6  4 16 15 24]
 [20 22  2 17 24]
 [20 18 16 17 23]
 [13 22 18 18  1]]
Modified Array : 
 [16 10 22 14 21  6 20 20 13 22 18 18  1 24 24 23]


### Assignment 3: Array Operations

1. Create two NumPy arrays of shape (3, 4) filled with random integers. Perform element-wise addition, subtraction, multiplication, and division.
2. Create a NumPy array of shape (4, 4) with values from 1 to 16. Compute the row-wise and column-wise sum.



In [5]:
import numpy as np
array1 = np.random.randint(1,21, size=(3,4))
array2 = np.random.randint(1,21, size=(3,4))
print(f' Original Array : \n {array1}')
print(f' Original Array : \n {array2}')

sub = array1[0][1] - array2[0][1]
print(f"Subs : {sub}")

 Original Array : 
 [[ 9  9  3  6]
 [ 7  4 11  7]
 [ 1  2  4  1]]
 Original Array : 
 [[13 16 18  2]
 [ 7 12 12 17]
 [ 2 20 16 12]]
Subs : -7


### Assignment 4: Statistical Operations

1. Create a NumPy array of shape (5, 5) filled with random integers. Compute the mean, median, standard deviation, and variance of the array.
2. Create a NumPy array of shape (3, 3) with values from 1 to 9. Normalize the array (i.e., scale the values to have a mean of 0 and a standard deviation of 1).



In [ ]:
import numpy as np 

array2 = np.random.randint(1,21, size=(5,5))
print(f' Original Array : \n {array2} \n')

mean = np.mean(array2)
median = np.median(array2)
std = np.std(array2)
variance = np.var(array2)
print(f' Mean: {mean}')
print(f' Standerd Deviation: {std}')
print(f' Median: {median}')
print(f' Variance: {variance}')

 Original Array : 
 [[11 16  5 18 15]
 [19 15 16  6  3]
 [16  4  1 16  1]
 [ 5 14 20 10 15]
 [13 18  9 17  4]] 

 Mean: 11.48
 Standerd Deviation: 5.994130462377342
 Median: 14.0
 Variance: 35.92960000000001


In [ ]:
import numpy as np 

array3 = np.random.randint(1,10, size=(3,3))
print(f' Original Array : \n {array3} \n')

mean = np.mean(array3)
std = np.std(array3)

normalzation = (array3 - mean)/ std
normalzation_rd = np.round(normalzation, 2)
print(f"Normalized array: \n {normalzation}")
print(f"Normalized array Rounded: \n {normalzation_rd}")


 Original Array : 
 [[2 7 2]
 [8 5 9]
 [4 5 6]] 

Normalized array: 
 [[-1.44337567  0.72168784 -1.44337567]
 [ 1.15470054 -0.14433757  1.58771324]
 [-0.57735027 -0.14433757  0.28867513]]
Normalized array Rounded: 
 [[-1.44  0.72 -1.44]
 [ 1.15 -0.14  1.59]
 [-0.58 -0.14  0.29]]


### Assignment 5: Broadcasting

1. Create a NumPy array of shape (3, 3) filled with random integers. Add a 1D array of shape (3,) to each row of the 2D array using broadcasting.
2. Create a NumPy array of shape (4, 4) filled with random integers. Subtract a 1D array of shape (4,) from each column of the 2D array using broadcasting.



In [16]:
import numpy as np 

array3 = np.random.randint(1,11, size=(3,3))
print(f' Original Array : \n {array3} \n')

row_arr = np.random.randint(1,11, size=(3,))
print(f' 1D Array : \n {row_arr} \n')

res = array3 + row_arr

print(f' Array after printing : \n {res} \n')




 Original Array : 
 [[ 3  8  3]
 [10  3  1]
 [ 6  9  1]] 

 1D Array : 
 [1 4 1] 

 Array after printing : 
 [[ 4 12  4]
 [11  7  2]
 [ 7 13  2]] 



In [18]:
import numpy as np 

array3 = np.random.randint(1,11, size=(4,4))
print(f' Original Array : \n {array3} \n')

row_arr = np.random.randint(1,11, size=(4,))
print(f' 1D Array : \n {row_arr} \n')

res = array3 - row_arr

print(f' Array after printing : \n {res} \n')

 Original Array : 
 [[10  4  5  2]
 [ 2  9  7  8]
 [ 8  2  9  5]
 [ 4  9  7 10]] 

 1D Array : 
 [7 3 4 6] 

 Array after printing : 
 [[ 3  1  1 -4]
 [-5  6  3  2]
 [ 1 -1  5 -1]
 [-3  6  3  4]] 



### Assignment 6: Linear Algebra

1. Create a NumPy array of shape (3, 3) representing a matrix. Compute its determinant, inverse, and eigenvalues.
2. Create two NumPy arrays of shape (2, 3) and (3, 2). Perform matrix multiplication on these arrays.



In [22]:
import numpy as np 

array3 = np.random.randint(1,11, size=(3,3))
print(f' Original Array : \n {array3} \n')

determinant = np.linalg.det(array3)
print(f' Determinant Array: {determinant}\n')

inverse = np.linalg.inv(array3)
print(f' Inverse Array: \n{inverse}\n')

eigenvalues = np.linalg.eigvals(array3)
print(f' Eigenvalues Array: {eigenvalues}')


 Original Array : 
 [[3 8 4]
 [8 8 2]
 [1 7 4]] 

 Determinant Array: 6.000000000000021

 Inverse Array: 
[[ 3.         -0.66666667 -2.66666667]
 [-5.          1.33333333  4.33333333]
 [ 8.         -2.16666667 -6.66666667]]

 Eigenvalues Array: [15.90400283+0.j         -0.45200141+0.41588248j -0.45200141-0.41588248j]


In [28]:
import numpy as np 

mat1 = np.random.randint(1,11, size=(2,3))
mat2 = np.random.randint(1,11, size=(3,2))
print(f' 2 x 3 Array : \n {mat1} \n')
print(f' 3 x 2 Array : \n {mat2} \n')

mult_matrix = np.dot(mat1 , mat2)

print(f"Matrix multiplication (dot) result: \n {mult_matrix}")

 2 x 3 Array : 
 [[3 9 2]
 [3 2 1]] 

 3 x 2 Array : 
 [[9 4]
 [2 2]
 [7 1]] 

Matrix multiplication (dot) result: 
 [[59 32]
 [38 17]]


### Assignment 7: Advanced Array Manipulation

1. Create a NumPy array of shape (3, 3) with values from 1 to 9. Reshape the array to shape (1, 9) and then to shape (9, 1).
2. Create a NumPy array of shape (5, 5) filled with random integers. Flatten the array and then reshape it back to (5, 5).



In [31]:
import numpy as np 

array3 = np.random.randint(1,9, size=(3,3))
print(f' Original Array : \n {array3} \n')

row_reshape = array3.reshape((1,9))
col_reshape = array3.reshape((9,1))
print(f' Row Reshape Array : \n {row_reshape} \n')
print(f' column Reshape Array : \n {col_reshape} \n')


 Original Array : 
 [[7 4 1]
 [6 7 5]
 [6 8 4]] 

 Row Reshape Array : 
 [[7 4 1 6 7 5 6 8 4]] 

 column Reshape Array : 
 [[7]
 [4]
 [1]
 [6]
 [7]
 [5]
 [6]
 [8]
 [4]] 



In [32]:
import numpy as np 

array3 = np.random.randint(1,9, size=(5,5))
print(f' Original Array : \n {array3} \n')

flatten_arr = array3.flatten()
reshape_matrix = flatten_arr.reshape((5,5))

print(f' Flatten Array : \n {flatten_arr} \n')
print(f' Reshaped original Array : \n {reshape_matrix} \n')

 Original Array : 
 [[4 4 4 3 3]
 [1 7 1 7 6]
 [8 7 2 3 5]
 [2 6 1 8 7]
 [4 3 1 1 2]] 

 Flatten Array : 
 [4 4 4 3 3 1 7 1 7 6 8 7 2 3 5 2 6 1 8 7 4 3 1 1 2] 

 Reshaped original Array : 
 [[4 4 4 3 3]
 [1 7 1 7 6]
 [8 7 2 3 5]
 [2 6 1 8 7]
 [4 3 1 1 2]] 



### Assignment 8: Fancy Indexing and Boolean Indexing

1. Create a NumPy array of shape (5, 5) filled with random integers. Use fancy indexing to extract the elements at the corners of the array.
2. Create a NumPy array of shape (4, 4) filled with random integers. Use boolean indexing to set all elements greater than 10 to 10.



In [37]:
import numpy as np 

array3 = np.random.randint(1,21, size=(5,5))
print(f' Original Array : \n {array3} \n')

fancy_arr = array3[[0,0,-1,-1],[0,-1,-1,0]]
print(f' Corner Array : \n {fancy_arr} \n')

 Original Array : 
 [[ 5 20 16 18 11]
 [14 10 12  1 14]
 [18  3  4  5 20]
 [ 6 20  9  2  1]
 [ 9  9 20 18  5]] 

 Corner Array : 
 [ 5 11  5  9] 



In [39]:
import numpy as np 

array3 = np.random.randint(1,21, size=(4,4))
print(f' Original Array : \n {array3} \n')

array3[array3>10] =10
array3[array3<5] =0
print(f' Boolean indexing Array : \n {array3} \n')


 Original Array : 
 [[18 14 10 20]
 [19  1  1  6]
 [ 8  1  4 19]
 [10  1 15 19]] 

 Boolean indexing Array : 
 [[10 10 10 10]
 [10  0  0  6]
 [ 8  0  0 10]
 [10  0 10 10]] 



### Assignment 9: Structured Arrays

1. Create a structured array with fields 'name' (string), 'age' (integer), and 'weight' (float). Add some data and sort the array by age.
2. Create a structured array with fields 'x' and 'y' (both integers). Add some data and compute the Euclidean distance between each pair of points.



In [41]:
data_type = [('name', 'U10'), ('age', 'i4'), ('weight', 'f4')]
data = np.array([('Alice', 25, 55.5), ('Bob', 30, 85.3), ('Charlie', 20, 65.2)], dtype=data_type)
print(f' Original Array : \n {data} \n')

sorted_data = np.sort(data, order='age')
print(f"Sorted array by age: \n {sorted_data}")


 Original Array : 
 [('Alice', 25, 55.5) ('Bob', 30, 85.3) ('Charlie', 20, 65.2)] 

Sorted array by age: 
 [('Charlie', 20, 65.2) ('Alice', 25, 55.5) ('Bob', 30, 85.3)]


In [42]:
data_type = [('x', 'i4'), ('y', 'i4')]
data = np.array([(1, 2), (3, 4), (5, 6)], dtype=data_type)
print(f' Original Array : \n {data} \n')

distances = np.sqrt((data['x'][:, np.newaxis] - data['x'])**2 + (data['y'][:, np.newaxis] - data['y'])**2)
print(f"Euclidean distances: \n {distances}")

 Original Array : 
 [(1, 2) (3, 4) (5, 6)] 

Euclidean distances: 
 [[0.         2.82842712 5.65685425]
 [2.82842712 0.         2.82842712]
 [5.65685425 2.82842712 0.        ]]


### Assignment 10: Masked Arrays

1. Create a masked array of shape (4, 4) with random integers and mask the elements greater than 10. Compute the sum of the unmasked elements.
2. Create a masked array of shape (3, 3) with random integers and mask the diagonal elements. Replace the masked elements with the mean of the unmasked elements.

In [43]:
import numpy.ma as ma 

array3 = np.random.randint(1,21, size=(4,4))
masked_array = ma.masked_greater(array3,10)

print(f"Original Array: \n {array3}")
print(f"Masked Array: \n {masked_array}")

sum_unmasked = masked_array.sum()
print(f'Unmaksed array: \n {sum_unmasked}')

Original Array: 
 [[20 12 11 15]
 [11 13 16 14]
 [10  5  4  3]
 [ 5  1  2 15]]
Masked Array: 
 [[-- -- -- --]
 [-- -- -- --]
 [10 5 4 3]
 [5 1 2 --]]
Unmaksed array: 
 30


In [45]:
import numpy.ma as ma 

array3 = np.random.randint(1,21, size=(3,3))
masked_array = ma.masked_array(array3, mask=np.eye(3, dtype=bool))

print(f"Original Array: \n {array3}")
print(f"Masked Array: \n {masked_array}")

mean_unmasked = masked_array.mean()
masked_array = masked_array.filled(mean_unmasked)

print(f"Modified Masked Array: \n {masked_array}")

Original Array: 
 [[ 7 18 11]
 [12 20  8]
 [ 8  1  2]]
Masked Array: 
 [[-- 18 11]
 [12 -- 8]
 [8 1 --]]
Modified Masked Array: 
 [[ 9 18 11]
 [12  9  8]
 [ 8  1  9]]
